CREATE TABLE IF NOT EXISTS houry_rate (
    id SERIAL PRIMARY KEY,
    amount DECIMAL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
