// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: department.sql

package sqlcdb

import (
	"context"
)

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT department_id,department_name FROM departments WHERE department_id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, departmentID int32) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, departmentID)
	var i Department
	err := row.Scan(&i.DepartmentID, &i.DepartmentName)
	return i, err
}
