// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: department.sql

package sqlcdb

import (
	"context"
)

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id,name FROM departments WHERE id = $1
`

type GetDepartmentByIDRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetDepartmentByID(ctx context.Context, id int32) (GetDepartmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i GetDepartmentByIDRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
