// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

type Department struct {
	DepartmentID int32 `json:"department_id"`
	// deaprtment name is unique
	DepartmentName string `json:"department_name"`
}
