// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	GetDepartmentByID(ctx context.Context, departmentID int32) (Department, error)
}

var _ Querier = (*Queries)(nil)
